
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 09:11:09 COT 2015
//----------------------------------------------------

package FlexCup1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUSCULA = 2;
  public static final int MAYUSCULA = 3;
  public static final int FINLINEA = 4;
  public static final int error = 1;
  public static final int ESPACIO = 5;
  public static final int EOF = 0;
}

